### ISSUE TITLE
Copyright date should be fixed

### ISSUE THREAD

**Issue by RaoOfPhysics** [cms-sw/cms-sw.github.io#50]
The starting year on the copyright notice should be the year when the text on the website was originally authored. Since CMS didn't exist back in 1954, we should fix this. :)

**Comment by ktf** [comment]
That's why it says "copyright CERN". ;) I also do not think CMS is a legal entity so the copyright cannot be attributed to it.

**Comment by RaoOfPhysics** [comment]
@ktf: Right, the copyright is indeed held by CERN ("for the benefit of the CMS Collaboration"), but the start date must be the date when the original content was written.

**Comment by ktf** [comment]
I've no idea when the some of the content was written, so I just played safe. ;-)

Nagging apart, feel free to change it and submit a PR, someone (not me, since I moved to ALICE and I do not have rights) will merge it.

**Comment by RaoOfPhysics** [comment]
> I moved to ALICE

:(

**Comment by RaoOfPhysics** [comment]
@ktf: Ok, I'll fix it. What year was CMSSW conceived in?

**Comment by ktf** [comment]
In the past, I found bits stating to be as far back as 1995 (which are
still owned by CMS / CERN because of CMS contribution policy), I wouldn't
exclude there is older fortran code.

**Comment by RaoOfPhysics** [comment]
@ktf: Ah, so it's somewhat nebulous. :(

**Comment by ktf** [comment]
Yes, indeed... :)

Anyways, given I've joined CERN and moved to the ALICE experiment, feel 
free to update it as you feel it's correct.

-- 
Ciao,
Giulio

On Thu, Jun 4, 2015 at 9:33 AM Achintya Rao <notifications@github.com> 
wrote:


@ktf: Ah, so it's somewhat nebulous. :(
